name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the feature.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you want this feature? What problem does it solve?

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Describe how the feature should work.

  - type: textarea
    id: additional
    attributes:
      label: Additional Notes
      description: Any other context or references.
